/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1;  
@SuppressWarnings("all")
public class row1StructBeanInfo extends java.beans.SimpleBeanInfo implements java.io.Serializable {
  /** Default serial version UID. */
  public static final int serialVersionUID = 1;
  private final static Class<row1Struct> currentClass = row1Struct.class;

  public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
          try {
        java.beans.PropertyDescriptor[] list = {
                  new java.beans.PropertyDescriptor("payload", currentClass, "getPayload", "setPayload"),
                };
        return list;
      } catch (java.beans.IntrospectionException iexErr) {
        throw new Error(iexErr.toString());
      }
      }

  public java.beans.BeanDescriptor getBeanDescriptor() {
    java.beans.BeanDescriptor desc = new java.beans.BeanDescriptor(currentClass);
    return desc;
  }
}
