/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class row1Struct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord, java.io.Serializable {
  /** Default serial version UID. */
  public static final int serialVersionUID = 1;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"row1Struct\",\"namespace\":\"local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1\",\"fields\":[{\"name\":\"payload\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"java.lang.String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.String payload;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return payload;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: payload = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'payload' field.
   */
  public java.lang.String getPayload() {
    return payload;
  }

  /**
   * Sets the value of the 'payload' field.
   * @param value the value to set.
   */
  public void setPayload(java.lang.String value) {
    this.payload = value;
  }

  /** Creates a new row1Struct RecordBuilder */
  public static local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder newBuilder() {
    return new local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder();
  }
  
  /** Creates a new row1Struct RecordBuilder by copying an existing Builder */
  public static local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder newBuilder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder other) {
    return new local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder(other);
  }
  
  /** Creates a new row1Struct RecordBuilder by copying an existing row1Struct instance */
  public static local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder newBuilder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct other) {
    return new local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder(other);
  }
  
  /**
   * RecordBuilder for row1Struct instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<row1Struct>
    implements org.apache.avro.data.RecordBuilder<row1Struct> {

    private java.lang.String payload;

    /** Creates a new Builder */
    private Builder() {
      super(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.payload)) {
        this.payload = data().deepCopy(fields()[0].schema(), other.payload);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing row1Struct instance */
    private Builder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct other) {
            super(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.SCHEMA$);
      if (isValidValue(fields()[0], other.payload)) {
        this.payload = data().deepCopy(fields()[0].schema(), other.payload);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'payload' field */
    public java.lang.String getPayload() {
      return payload;
    }
    
    /** Sets the value of the 'payload' field */
    public local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder setPayload(java.lang.String value) {
      validate(fields()[0], value);
      this.payload = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'payload' field has been set */
    public boolean hasPayload() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'payload' field */
    public local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row1Struct.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[0] = false;
      return this;
    }


    public row1Struct build() {
      try {
        row1Struct record = new row1Struct();
        record.payload = fieldSetFlags()[0] ? this.payload : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}