/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class row2Struct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord, java.io.Serializable {
  /** Default serial version UID. */
  public static final int serialVersionUID = 1;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"row2Struct\",\"namespace\":\"local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1\",\"fields\":[{\"name\":\"id\",\"type\":[\"int\",\"null\"]},{\"name\":\"name\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"java.lang.String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.Integer id;
   public java.lang.String name;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /** Creates a new row2Struct RecordBuilder */
  public static local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder newBuilder() {
    return new local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder();
  }
  
  /** Creates a new row2Struct RecordBuilder by copying an existing Builder */
  public static local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder newBuilder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder other) {
    return new local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder(other);
  }
  
  /** Creates a new row2Struct RecordBuilder by copying an existing row2Struct instance */
  public static local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder newBuilder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct other) {
    return new local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder(other);
  }
  
  /**
   * RecordBuilder for row2Struct instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<row2Struct>
    implements org.apache.avro.data.RecordBuilder<row2Struct> {

    private java.lang.Integer id;
    private java.lang.String name;

    /** Creates a new Builder */
    private Builder() {
      super(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing row2Struct instance */
    private Builder(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct other) {
            super(local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder setId(java.lang.Integer value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.String getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public local_project.sparkstreaming_local_basics_j06_230_sparkjob1_0_1.row2Struct.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }


    public row2Struct build() {
      try {
        row2Struct record = new row2Struct();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}